<?php

// Список существующих статусов.
$statuses = LinemediaAutoOrder::getStatusesList();

$LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY = (string) $_POST['LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY', $LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY);

$LM_AUTO_MAIN_STATUS_ID_AFTER_PAY = (string) $_POST['LM_AUTO_MAIN_STATUS_ID_AFTER_PAY'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_ID_AFTER_PAY', $LM_AUTO_MAIN_STATUS_ID_AFTER_PAY);

$LM_AUTO_MAIN_CANCEL_STATUS_ID = (string) $_POST['LM_AUTO_MAIN_CANCEL_STATUS_ID'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_CANCEL_STATUS_ID', $LM_AUTO_MAIN_CANCEL_STATUS_ID);

$LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST', $LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST);

$LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST', $LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST);

$LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT', $LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT);

$LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID = (string) $_POST['LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID', $LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID);

foreach ($statuses as $status) {
    $LM_AUTO_MAIN_STATUS_COLOR = strtoupper((string) $_POST['LM_AUTO_MAIN_STATUS_COLOR_' . $status['ID']]);
    COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_COLOR_' . $status['ID'], $LM_AUTO_MAIN_STATUS_COLOR);
    
    $LM_AUTO_MAIN_STATUS_COLOR = strtoupper((string) $_POST['LM_AUTO_MAIN_PUBLIC_STATUS_COLOR_' . $status['ID']]);
    COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_PUBLIC_STATUS_COLOR_' . $status['ID'], $LM_AUTO_MAIN_STATUS_COLOR);
}
