<?php

$LM_AUTO_MAIN_PRINT_TEMPLATE_DISABLE = serialize((array) $_POST['LM_AUTO_MAIN_PRINT_TEMPLATE_DISABLE']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_PRINT_TEMPLATE_DISABLE', $LM_AUTO_MAIN_PRINT_TEMPLATE_DISABLE);


$LM_AUTO_MAIN_DEFERRED_PAYMENT = (string) $_POST['LM_AUTO_MAIN_DEFERRED_PAYMENT'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_DEFERRED_PAYMENT', $LM_AUTO_MAIN_DEFERRED_PAYMENT);

$LM_AUTO_MAIN_DECREASE_QUANTITY_PRODUCT_ORDERING = (string) $_POST['LM_AUTO_MAIN_DECREASE_QUANTITY_PRODUCT_ORDERING'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_DECREASE_QUANTITY_PRODUCT_ORDERING', $LM_AUTO_MAIN_DECREASE_QUANTITY_PRODUCT_ORDERING);

$LM_AUTO_MAIN_GROUP_TRANSFER_BACK = (string) $_POST['LM_AUTO_MAIN_GROUP_TRANSFER_BACK'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_GROUP_TRANSFER_BACK', $LM_AUTO_MAIN_GROUP_TRANSFER_BACK);
