<?php

$LM_AUTO_MAIN_STATUS_REQUESTED = (string) $_POST['LM_AUTO_MAIN_STATUS_REQUESTED'];
COption::SetOptionString('linemedia.auto', 'LM_AUTO_MAIN_STATUS_REQUESTED', $LM_AUTO_MAIN_STATUS_REQUESTED);

$LM_AUTO_MAIN_STATUS_REJECTED = (string) $_POST['LM_AUTO_MAIN_STATUS_REJECTED'];
COption::SetOptionString('linemedia.auto', 'LM_AUTO_MAIN_STATUS_REJECTED', $LM_AUTO_MAIN_STATUS_REJECTED);

$LM_AUTO_MAIN_STATUS_STORED = (string) $_POST['LM_AUTO_MAIN_STATUS_STORED'];
COption::SetOptionString('linemedia.auto', 'LM_AUTO_MAIN_STATUS_STORED', $LM_AUTO_MAIN_STATUS_STORED);
