<?php

$LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES = $_POST['LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES', $LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES);

$LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES_ORIGINAL = $_POST['LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES_ORIGINAL'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES_ORIGINAL', $LM_AUTO_MAIN_SEARCH_TECDOC_CROSSES_ORIGINAL);

$LM_AUTO_MAIN_SEARCH_LINEMEDIA_CROSSES = $_POST['LM_AUTO_MAIN_SEARCH_LINEMEDIA_CROSSES'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_SEARCH_LINEMEDIA_CROSSES', $LM_AUTO_MAIN_SEARCH_LINEMEDIA_CROSSES);

$LM_AUTO_MAIN_SEARCH_SIMPLE_CROSSES = $_POST['LM_AUTO_MAIN_SEARCH_SIMPLE_CROSSES'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_SEARCH_SIMPLE_CROSSES', $LM_AUTO_MAIN_SEARCH_SIMPLE_CROSSES);

