<?php

$LM_AUTO_MAIN_LOCAL_SHOW_ONLY_IN_STOCK = (string) $_POST['LM_AUTO_MAIN_LOCAL_SHOW_ONLY_IN_STOCK'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_LOCAL_SHOW_ONLY_IN_STOCK', $LM_AUTO_MAIN_LOCAL_SHOW_ONLY_IN_STOCK);

$LM_AUTO_MAIN_GLOBAL_MENU_HIDE_STORE = (string) $_POST['LM_AUTO_MAIN_GLOBAL_MENU_HIDE_STORE'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_GLOBAL_MENU_HIDE_STORE', $LM_AUTO_MAIN_GLOBAL_MENU_HIDE_STORE);

$LM_AUTO_MAIN_MENU_HIDE = serialize((array) $_POST['LM_AUTO_MAIN_MENU_HIDE']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_MENU_HIDE', $LM_AUTO_MAIN_MENU_HIDE);
